// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy-8ZPApBZZ-wfumJlKmAKOLItIkAxyPo',
    appId: '1:428095597804:web:b5cf967bfdf690bca0c9c9',
    messagingSenderId: '428095597804',
    projectId: 'flutter-firebase-239be',
    authDomain: 'flutter-firebase-239be.firebaseapp.com',
    storageBucket: 'flutter-firebase-239be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVUCP6_M6DvhXpckfAgkQsYShBc8XDfj4',
    appId: '1:428095597804:android:1a9bae047f836a2aa0c9c9',
    messagingSenderId: '428095597804',
    projectId: 'flutter-firebase-239be',
    storageBucket: 'flutter-firebase-239be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7AN1z_4AqTMVgKc_7_lEHRzoh4oIqXQM',
    appId: '1:428095597804:ios:f5074f79bbdd7417a0c9c9',
    messagingSenderId: '428095597804',
    projectId: 'flutter-firebase-239be',
    storageBucket: 'flutter-firebase-239be.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7AN1z_4AqTMVgKc_7_lEHRzoh4oIqXQM',
    appId: '1:428095597804:ios:f5074f79bbdd7417a0c9c9',
    messagingSenderId: '428095597804',
    projectId: 'flutter-firebase-239be',
    storageBucket: 'flutter-firebase-239be.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
